version: "3.8"

services:

  db:
    image: postgres:13.1-alpine
    container_name: db
    mem_limit: 700m
    environment:
         - POSTGRES_USER=demo_user
         - POSTGRES_PASSWORD=demo_user
         - POSTGRES_DB=demo
    command: postgres -c 'hba_file= /etc/postgresql/12/main/pg_hba.conf'

    
  
  incidentcreation:
    image: finleaptest/incident_creation:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/demo
        - SPRING_DATASOURCE_USERNAME=demo_user
        - SPRING_DATASOURCE_PASSWORD=demo@user
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update 
   
         
 

